site_name: HITWH-CS
nav:
  - 主页:
    - index.md
    - 课程模版: template.md
    - 贡献指南: manual.md
  - 通识课:
    - 介绍: general/index.md 
  - 数理基础课:
    - 介绍: basic/index.md
  - 文化素质课:
    - 介绍: culture/index.md
  - 计算机专业课:
    - 介绍: major/index.md
  - 实验室:
    - 介绍: labs/index.md
  - 分享会:
    - 介绍: salon/index.md
  - CTF-WP:
    - 介绍: CTF-WP/index.md



theme:
  name: 'material'
  language: 'zh'
  # logo: images/icon.png
  icon:
    logo: material/notebook-outline
    repo: fontawesome/brands/github
    edit: material/pencil
  #custom_dir: overrides
  favicon: images/icon.png
  features:
    - content.code.annotate
    - content.action.edit
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections
  font:
    # text: Noto Serif SC
    code: JetBrains Mono
  palette:
    - scheme: default

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - https://fonts.googleapis.com/css?family=Noto+Serif+SC:300,300i,400,400i,700,700i&display=fallback
  - css/custom.css
